###

GET http://localhost:3000/student

###

GET http://localhost:3000/student/1234567892

###

GET http://localhost:3000/student?name=John 44

###

POST http://localhost:3000/student
Content-Type: application/json

{
    "_id": "123456781",
    "name": "John",
    "avaterUrl": "https://www.google.com"
    
}

###

PUT http://localhost:3000/student

###

DELETE http://localhost:3000/student
