###

GET http://localhost:3000/student

###

GET http://localhost:3000/student/1234567892

###

GET http://localhost:3000/student?name=John 44

###

POST http://localhost:3000/student
Content-Type: application/json

{
    "name": "John 44",
    "age": "20",
    "_id": "12345678921"
}

###

PUT http://localhost:3000/student

###

DELETE http://localhost:3000/student
